### ISSUE TITLE
yoga.Config.create not supported

### ISSUE THREAD

**Issue by Skywalker13** [rickbutton/yoga-wasm#1]
Hello,

Something that works with `yoga-layout` but not with your module:

```js
const config = yoga.Config.create();
```

`TypeError: yoga.Config.create is not a function`

**Comment by Skywalker13** [comment]
I try to use your module in replacement of yoga-layout-prebuilt with react-pdf...

**Comment by rickbutton** [comment]
I believe I've resolved this with PR #3 , published yoga-wasm version `0.0.2`. Please check it out and let me know! Feel free to close this if you find it fixed.

**Comment by Skywalker13** [comment]
This problem is fixed, thanks
